# Web pipeline
# Added trigger
# publish artifacts

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - 'README.md' 

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPublish
  displayName: 'Build and Publish'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 6'
    inputs:
      version: '6.x'
  - task: DotNetCoreCLI@2
    displayName: '.NET Restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    displayName: '.NET Build'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: '.NET Publish'
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifacts'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'web'
      publishLocation: 'pipeline'